insert into VT_PHOENIX_ATTRIBUTE_LOV (LOV_ID, LOV_DESCRIPTION, LOV_NAME) values (-1, 'Dictionary1', 'Dictionary1');
insert into VT_PHOENIX_ATTRIBUTE_LOV_VALUE (LOV_ID, LOV_VALUE_ID, LOV_VALUE, LOV_DESCRIPTION, LOV_ORDER) values (-1, -1, 'val1', 'Val1', 1);
insert into VT_PHOENIX_ATTRIBUTE_LOV_VALUE (LOV_ID, LOV_VALUE_ID, LOV_VALUE, LOV_DESCRIPTION, LOV_ORDER) values (-1, -2, 'val2', 'Val2', 2);
insert into VT_PHOENIX_ATTRIBUTE_LOV_VALUE (LOV_ID, LOV_VALUE_ID, LOV_VALUE, LOV_DESCRIPTION, LOV_ORDER) values (-1, -3, 'val3', 'Val3', 3);
insert into VT_PHOENIX_ATTRIBUTE_LOV_VALUE (LOV_ID, LOV_VALUE_ID, LOV_VALUE, LOV_DESCRIPTION, LOV_ORDER) values (-1, -4, 'val4', 'Val4', 4);

insert into VT_PHOENIX_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_NAME, ATTRIBUTE_LABEL, ATTRIBUTE_TYPE, ATTRIBUTE_DESCRIPTION, ATTRIBUTE_LENGTH, LOV_ID) values (-1, 'attr1', 'Attr1', 'TEXT', 'Attr1 desc', 200, null);
insert into VT_PHOENIX_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_NAME, ATTRIBUTE_LABEL, ATTRIBUTE_TYPE, ATTRIBUTE_DESCRIPTION, ATTRIBUTE_LENGTH, LOV_ID) values (-2, 'attr2', 'Attr2', 'TEXT', 'Attr2 desc', 100, null);
insert into VT_PHOENIX_ATTRIBUTE (ATTRIBUTE_ID, ATTRIBUTE_NAME, ATTRIBUTE_LABEL, ATTRIBUTE_TYPE, ATTRIBUTE_DESCRIPTION, ATTRIBUTE_LENGTH, LOV_ID) values (-3, 'attr3', 'Attr3', 'SELECT', 'Attr3 desc', null, -1);
 