INSERT INTO UT_OPERATION (ID, VERSION, USERNAME, FOLDER_ID, CREATE_DATE, STATUS) 
	VALUES (-1, 1, 'bpl3195', 431, TO_DATE('2016-09-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'CREATED');
	
INSERT INTO UT_OPERATION_TREE (OPERATION_ID, NODE_ID, NODE_PARENT_ID, VERSION, NODE_TEXT, NODE_TYPE, REV) 
	VALUES (-1, -101, null, 1, 'Marine', 'S', null);
INSERT INTO UT_OPERATION_TREE (OPERATION_ID, NODE_ID, NODE_PARENT_ID, VERSION, NODE_TEXT, NODE_TYPE, REV) 
	VALUES (-1, -1001, -101, 1, 'Migrated Park Document', 'D', 1);	
INSERT INTO UT_OPERATION_TREE (OPERATION_ID, NODE_ID, NODE_PARENT_ID, VERSION, NODE_TEXT, NODE_TYPE, REV) 
	VALUES (-1, -10001, -1001, 1, 'parkDocument.docx', 'F', null);

INSERT INTO UT_OPERATION_CONFLICT (ID, OPERATION_ID, TREE_NODE_ID, CONFLICT_TYPE) 
	VALUES (-1, -1, -101, 'FOLDER_NAME');